spring:
  application:
    name: auth
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: 0

jwt:
  access-token-validity-in-milliseconds: 300000 # 5 minutes
  refresh-token-validity-in-milliseconds: 604800000 # 7 days
  internal-token-validity-in-milliseconds: 600000 # 1 minute
  issuer: ${JWT_ISSUER}
  access-validity-seconds: 900
server:
  port: 8083

kms:
  jwt:
    key-id: ${KMS_JWT_KEY_ID}        # 예: arn:aws:kms:ap-northeast-2:111111111111:key/xxxx or alias/jwt-internal

aws:
 region: ap-northeast-2