spring:
  main:
    lazy-initialization: true
  application:
    name: auth
  config:
    import: optional:file:.env[.properties]
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
  profiles:
    active: dev

server:
  port: 8083

log:
  salt: ${LOG_SALT:default_salt_for_dev}
