spring:
  main:
    lazy-initialization: true
  application:
    name: auth
  config:
    import: optional:file:.env[.properties]


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true


server:
  port: 8083


